//LOCALHOST
###
GET http://localhost:3000 HTTP/1.1
###
Get all contacts GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/650b9e45d7cae14ab0345b7c HTTP/1.1
###
GET http://localhost:3000/contacts/650b9e45d7cae14ab0345b7d HTTP/1.1
###
GET http://localhost:3000/contacts/650b9e45d7cae14ab0345b7e HTTP/1.1
###
GET http://localhost:3000/contacts/650b9e45d7cae14ab0345b7f HTTP/1.1



//PRODUCTION Deploy
###
GET https://lesson02-ybz1.onrender.com HTTP/1.1
###
GET https://lesson02-ybz1.onrender.com/contacts HTTP/1.1
###
GET https://teresalesson01.onrender.com/contacts/650b9e45d7cae14ab0345b7c HTTP/1.1
###
GET https://lesson02-ybz1.onrender.com/contacts/650b9e45d7cae14ab0345b7d  HTTP/1.1
###
GET https://lesson02-ybz1.onrender.com/contacts/650b9e45d7cae14ab0345b7e HTTP/1.1
###
GET https://lesson02-ybz1.onrender.com/contacts/650b9e45d7cae14ab0345b7f HTTP/1.1
